# Generated by Django 3.0.8 on 2020-11-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('preownedprice', models.IntegerField(blank=True, null=True)),
                ('negameprice', models.IntegerField(blank=True, null=True)),
                ('platform', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('Text', models.TextField()),
            ],
        ),
    ]
