# Generated by Django 3.0.8 on 2020-11-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='upload_date',
        ),
    ]
