# Generated by Django 3.0.8 on 2020-11-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201129_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
