# Generated by Django 3.0.8 on 2020-11-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_gamedata_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='gamenum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
