# Generated by Django 3.0.8 on 2020-12-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='negameprice',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='preownedprice',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='newgameprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Customer'),
        ),
    ]
